#!/usr/bin/env python3
"""Render a user-facing GameLife HTML workbench from the bundled assets."""

from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path
from typing import Any

try:
    from .validate_state import load_state
except ImportError:  # Running the file directly from scripts/.
    from validate_state import load_state


ASSET_NAMES = ("gamelife.html", "gamelife.css", "gamelife.js")
BOOTSTRAP_NAME = "gamelife-bootstrap.js"
BOOTSTRAP_MARKER = '<script src="./gamelife.js" defer></script>'


def _bootstrap_source(state: dict[str, Any] | None) -> str:
    payload = json.dumps(state, ensure_ascii=False, separators=(",", ":")) if state else "null"
    return f'''// Generated by render_workbench.py. Do not commit personal state.\nwindow.GAMELIFE_INITIAL_STATE = {payload};\nif (window.GAMELIFE_INITIAL_STATE) {{\n  try {{\n    const key = "gamelife-skill:state:v1";\n    if (!window.localStorage.getItem(key)) window.localStorage.setItem(key, JSON.stringify(window.GAMELIFE_INITIAL_STATE));\n  }} catch (error) {{\n    // The workbench still runs with its bundled demo state when storage is unavailable.\n  }}\n}}\n'''


def render(output_dir: str | Path, state_path: str | Path | None = None) -> Path:
    output = Path(output_dir).resolve()
    source_dir = Path(__file__).resolve().parents[3] / "assets"
    output.mkdir(parents=True, exist_ok=True)

    state = load_state(state_path) if state_path else None
    for name in ASSET_NAMES:
        shutil.copy2(source_dir / name, output / name)

    html_path = output / "gamelife.html"
    html = html_path.read_text(encoding="utf-8")
    if BOOTSTRAP_MARKER not in html:
        raise RuntimeError(f"cannot find JavaScript marker in {html_path}")
    html = html.replace(
        BOOTSTRAP_MARKER,
        f'<script src="./{BOOTSTRAP_NAME}" defer></script>\n    {BOOTSTRAP_MARKER}',
        1,
    )
    html_path.write_text(html, encoding="utf-8")
    (output / BOOTSTRAP_NAME).write_text(_bootstrap_source(state), encoding="utf-8")
    return html_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, help="Directory for the rendered workbench")
    parser.add_argument("--state", help="Optional validated GameLife state JSON")
    args = parser.parse_args()
    html_path = render(args.output_dir, args.state)
    print(f"[OK] rendered GameLife workbench: {html_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
